### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by KristjanESPERANTO** [dierckxtom/MMM-Recyclecollection#1]
It would be nice if you could add a screenshot to your repository. This will allow users to see what the module looks like, and it will also be used in [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/).

**Comment by dierckxtom** [comment]
Updated

**Comment by KristjanESPERANTO** [comment]
Nice. Now one can see the screenshot in the README, but for showing up in the new module list it has to be in the repository and not in your personal GitHub space.
